/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import javax.swing.JFrame;

/**
 *
 * @author HuyTuan
 */
public class AlertUnknowAccountDialog extends javax.swing.JDialog {

    /**
     * Creates new form AlertUnknowAccountDialog
     * 
     */
    
    public AlertUnknowAccountDialog(JFrame parent) {
        super(parent);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void showAlert() {
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnCloseDialog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(642, 420));
        setModal(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(642, 420));

        bgPanel.setBackground(new java.awt.Color(0, 0, 0));
        bgPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 102), 3, true));
        bgPanel.setMinimumSize(new java.awt.Dimension(642, 420));
        bgPanel.setPreferredSize(new java.awt.Dimension(642, 420));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/error_dialog.PNG"))); // NOI18N
        jLabel19.setMaximumSize(new java.awt.Dimension(640, 328));
        jLabel19.setMinimumSize(new java.awt.Dimension(640, 328));
        jLabel19.setPreferredSize(new java.awt.Dimension(640, 328));
        bgPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 320));

        btnCloseDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/Ok_Dialog.PNG"))); // NOI18N
        btnCloseDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseDialogMouseClicked(evt);
            }
        });
        bgPanel.add(btnCloseDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseDialogMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseDialogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlertUnknowAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlertUnknowAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlertUnknowAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlertUnknowAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlertUnknowAccountDialog dialog = new AlertUnknowAccountDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel btnCloseDialog;
    private javax.swing.JLabel jLabel19;
    // End of variables declaration//GEN-END:variables
}
