/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import entities.Account;
import entities.Product;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import services.StringUtils;

/**
 *
 * @author HuyTuan
 */
public class ProductCard extends javax.swing.JPanel {

    /**
     * Creates new form ProductCard
     */
    public String producerName = "";
    public int productPrice = 0;
    public String imgName;
    private JFrame parentContainer = null;
    private Account account = null;
    private int id;
    private String productName;
    private String category;

    public ProductCard() {
        initComponents();
    }

    public ProductCard(int id, String name, String producer, String category, int price, String imgName, JFrame parent, Account ac) {
        initComponents();
        this.labelName.setText(name);
        this.labelProducer.setText(producer);
        producerName = producer;
        this.labelCategory.setText(category);
        productPrice = price;
        this.imgName = imgName;
        this.labelPrice.setText(new StringUtils().convertToPrice(price) + " VND / Ngày");
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src/resources/sanpham/" + imgName));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(350, 200, img.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        labelImage.setIcon(imageIcon);
        parentContainer = parent;
        account = ac;
        this.id = id;
        productName = name;
        this.category = category;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labelProducer = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        labelCategory = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        btnRent = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setMaximumSize(new java.awt.Dimension(390, 500));
        setMinimumSize(new java.awt.Dimension(390, 500));
        setPreferredSize(new java.awt.Dimension(390, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Tên sản phẩm");
        add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 350, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Nhà sản xuất:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 40));

        labelProducer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelProducer.setText("Honda");
        add(labelProducer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 110, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Loại xe:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, 40));

        labelCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCategory.setText("Xe tay ga");
        add(labelCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, 40));

        labelPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelPrice.setForeground(new java.awt.Color(255, 0, 0));
        labelPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrice.setText("100.000 VND / Ngày");
        add(labelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 390, 40));

        btnRent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/thue_ngay.PNG"))); // NOI18N
        btnRent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRentMouseClicked(evt);
            }
        });
        add(btnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, 60));

        labelImage.setMinimumSize(new java.awt.Dimension(350, 200));
        labelImage.setPreferredSize(new java.awt.Dimension(350, 200));
        add(labelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentMouseClicked
        // TODO add your handling code here:
        if (account == null) {
            new AlertUnknowAccountDialog(parentContainer).showAlert();
            return;
        }
        new LeasePanel(parentContainer, 
                new Product(productName, productPrice, imgName, category, producerName, id),
                account
        );
    }//GEN-LAST:event_btnRentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnRent;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelProducer;
    // End of variables declaration//GEN-END:variables
}
